package dambi;
import java.util.ArrayList;

import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

@RestController // This means that this class is a Controller
@RequestMapping(path="/jatetxeak") // This means URL's start with /demo (after Application path)
public class MainController {
  @Autowired // This means to get the bean called userRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private JatetxeaRepository jatetxeaRepository;
  private HelbideaRepository helbideaRepository;

  @PostMapping(path="/berria") // Map ONLY POST Requests
  public @ResponseBody String addNewJatetxe (@RequestParam String Jatetxeizena
      , @RequestParam String mota, @RequestParam Integer Helbideid, @RequestParam String ordutegia, @RequestParam String helbidea, @RequestParam Float prezioa) {
    // @ResponseBody means the returned String is the response, not a view name
    // @RequestParam means it is a parameter from the GET or POST request

    Jatetxea n = new Jatetxea();
    Helbidea h = new Helbidea();
    ArrayList <Helbidea> aHel= new ArrayList<Helbidea>();
    n.setIzena(Jatetxeizena);
    n.setMota(mota);
    h.setId(Helbideid);
    h.setHelbidea(helbidea);
    h.setOrdutegia(ordutegia);
    h.setPrezioa(prezioa);
    aHel.add(h);
    n.setHelbidea(aHel);
    jatetxeaRepository.save(n);
    helbideaRepository.save(h);

    return "Saved";
  }

  @GetMapping(path="/danak")
  public @ResponseBody Iterable<Jatetxea> getAllJatetxeak() {
    // This returns a JSON or XML with the users
    return jatetxeaRepository.findAll();
  }
  
}
